---
output:
  pdf_document: default
  html_document: default
---
```{r}
link='https://github.com/SamHenkels47/samhenkels2/raw/main/dataproject2.xlsx'
mydata=rio::import(link)
mydata
```
```{r}
library(reshape2)

melt(mydata,id.vars="Description")

```
```{r}
mydataLong=melt(mydata,id.vars="Description")
names(mydataLong)[2]="year" #renaming second name
# year as an ordinal factor!
mydataLong$year=factor(mydataLong$year,
                       levels = c("ten","fifteen","twenty"),
                       ordered = TRUE)
```

Now to ggplot!

```{r}
library(ggplot2)
base=ggplot(data=mydataLong,
            aes(x=year,
                y=value,
                fill=Description))+ scale_x_discrete(labels = c('2010','2015','2020'))
base + geom_bar(stat="identity") 
```

just in case:
```{r}
plot1=base + geom_bar(stat="identity") + 
    scale_y_continuous(labels = scales::number) # requires library "scales"
```

```{r}
titleText='Exports from Oregon'
sourceText='Source: US Census Bureau'
descriptionText='Export Clasification'

plot2 = plot1 + labs(title=titleText,
                     x ="Year", 
                     y = "Exports in Million $ ",
                     caption = sourceText) 

plot2
```
```{r}
plot3 = plot2 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot3
```

```{r}
plot4 = plot3 + scale_x_discrete("Year", labels = c ("ten" = "2010","fifteen"= "2015", "twenty" = "2020"))

plot4
```


```{r}
plot5 = plot4 +  geom_text(aes(label = value),position = position_stack(vjust = 0.5,), size = 1.6)

plot5
```
```{r}
saveRDS(plot5,file = 'chart2.rds')
saveRDS(plot5,file='chart2.rds')

```
